#!/usr/bin/env bash

RECIPE_BASE=$(dirname $0)
DISTRO_ID=$(basename $RECIPE_BASE)
DISTRO_NAME="Ubuntu 14.04 mini"

config(){
	echo "label $DISTRO_ID"
	echo "  menu label ^$DISTRO_NAME"
	echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/linux"
	echo "  append     boot=casper netboot=nfs nfsroot=$NFSHOST:$BASE_SYSTEMS/$DISTRO_ID/ initrd=$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.gz"

	echo "label $DISTRO_ID-preseed-default"
	echo "  menu label Install Ubuntu 14.04 ^Server"
	echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/linux"
	echo "  append     boot=casper netboot=nfs nfsroot=$NFSHOST:$BASE_SYSTEMS/$DISTRO_ID/ initrd=$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.gz priority=critical interface=auto locale=en_US.UTF-8 preseed/url=tftp://$NFSHOST/$BASE_SYSTEMS_rel/$DISTRO_ID/preseeds/server.cfg"

	echo "label $DISTRO_ID-preseed-default"
	echo "  menu label Install Ubuntu 14.04 ^Desktop"
        echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/linux"
	echo "  append     boot=casper netboot=nfs nfsroot=$NFSHOST:$BASE_SYSTEMS/$DISTRO_ID/ initrd=$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.gz priority=critical interface=auto locale=en_US.UTF-8 preseed/url=tftp://$NFSHOST/$BASE_SYSTEMS_rel/$DISTRO_ID/preseeds/desktop.cfg"

}

installation(){
	iso=$(mktemp)
	dir=$(mktemp -d)
	wget http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/mini.iso -O $iso
	mount $iso $dir
	cp -r $dir $BASE_SYSTEMS/$DISTRO_ID
	cp -r $RECIPE_BASE/preseeds/ $BASE_SYSTEMS/$DISTRO_ID
	umount $dir
	rmdir $dir
	rm $iso
}

if [[ ! -d $BASE_SYSTEMS/$DISTRO_ID && -n "$1" && "x$1" == "xinstall" ]]; then
	installation
fi

if [[ -n "$1" && "x$1" == "xconfig" ]]; then
	config
fi
