#!/usr/bin/env bash

RECIPE_BASE=$(dirname $0)
DISTRO_ID=$(basename $RECIPE_BASE)
DISTRO_NAME="Ubuntu 14.04"

config(){
	echo "label $DISTRO_ID"
	echo "  menu label Boot ^$DISTRO_NAME mini"
	echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/linux"
	echo "  append     initrd=$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.gz"

	echo "label $DISTRO_ID-preseed-default"
	echo "  menu label Install $DISTRO_NAME ^Server"
	echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/linux"
	echo "  append     initrd=$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.gz priority=critical interface=auto locale=en_US.UTF-8 preseed/url=tftp://$NFSHOST/$BASE_SYSTEMS_rel/$DISTRO_ID/preseeds/server.cfg"

	echo "label $DISTRO_ID-preseed-default"
	echo "  menu label Install $DISTRO_NAME ^Desktop"
        echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/linux"
	echo "  append     initrd=$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.gz priority=critical interface=auto locale=en_US.UTF-8 preseed/url=tftp://$NFSHOST/$BASE_SYSTEMS_rel/$DISTRO_ID/preseeds/desktop.cfg"
}

config_ipxe(){

	cat <<-END
	:menujump-$DISTRO_ID
	item --key I menu-$DISTRO_ID Install $DISTRO_NAME

	item --menu ubu14 $DISTRO_ID-desktop Install $DISTRO_NAME Desktop
	item --menu ubu14 $DISTRO_ID-server  Install $DISTRO_NAME Server
	item --menu ubu14 $DISTRO_ID-plain  Install $DISTRO_NAME
	goto backjump-$DISTRO_ID

	:menu-$DISTRO_ID
	menu Installation $DISTRO_NAME
	item
	item --key d $DISTRO_ID-desktop Install $DISTRO_NAME Desktop
	item --key s $DISTRO_ID-server  Install $DISTRO_NAME Server
	item
	item --gap -- -------------------------  CONFIGURATION  -------------------------------
	item --key h $DISTRO_ID-hostname Set hostname for fresh installation
	item
	item --gap -- -------------------------  SPECIAL  -------------------------------
	item $DISTRO_ID-plain Run Plain installation without preseed
	item
	item --key 0x08 back Back to top menu...
	choose selected && goto \${selected} || goto start

	:$DISTRO_ID-plain
	kernel $BASEURL_HTTP/$BASE_SYSTEMS_rel/$DISTRO_ID/linux
	initrd $BASEURL_HTTP/$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.gz
	boot || goto failed

	:$DISTRO_ID-desktop
	kernel $BASEURL_HTTP/$BASE_SYSTEMS_rel/$DISTRO_ID/linux priority=critical interface=auto locale=en_US.UTF-8 preseed/url=$BASEURL_HTTP/$BASE_SYSTEMS_rel/$DISTRO_ID/preseeds/desktop.cfg \${hostparam}
	initrd $BASEURL_HTTP/$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.gz
	boot || goto failed

	:$DISTRO_ID-server
	kernel $BASEURL_HTTP/$BASE_SYSTEMS_rel/$DISTRO_ID/linux priority=critical interface=auto locale=en_US.UTF-8 preseed/url=$BASEURL_HTTP/$BASE_SYSTEMS_rel/$DISTRO_ID/preseeds/server.cfg \${hostparam}
	initrd $BASEURL_HTTP/$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.gz
	boot || goto failed

	:$DISTRO_ID-hostname
	echo -n Please enter a hostname:
	read hostname
	set hostparam hostname=\${hostname}
	goto menu-$DISTRO_ID
	END

}

extract_iso(){
	if command -v osirrox >/dev/null 2>&1; then
		osirrox -indev $1 -extract / $2
	else
		dir=$(mktemp -d)
		mount $1 $dir
		cp -r $dir $2
		umount $dir
		rmdir $dir
	fi
}

installation(){
	iso=$(mktemp)
	wget http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/mini.iso -O $iso
	exctract_iso $iso $BASE_SYSTEMS/$DISTRO_ID
	rm $iso
}

update(){
	[ ! -d $BASE_SYSTEMS/$DISTRO_ID/preseeds ] && mkdir $BASE_SYSTEMS/$DISTRO_ID/preseeds
	for seed in $RECIPE_BASE/preseeds/*; do
		envsubst < $seed > $BASE_SYSTEMS/$DISTRO_ID/preseeds/$(basename $seed)
	done
}

case "$1" in
	install)
		[[ ! -d $BASE_SYSTEMS/$DISTRO_ID ]] && installation
		update
		;;
	config)
		config
		;;
	config_ipxe)
		config_ipxe
		;;
esac
