#!/usr/bin/env bash

RECIPE_BASE=$(dirname $0)
DISTRO_ID=$(basename $RECIPE_BASE)
DISTRO_NAME=Memtest

config(){
	echo "label $DISTRO_ID"
	echo "  menu label ^$DISTRO_NAME"
	echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/mt86plus"
}

installation(){
	mkdir -p $BASE_SYSTEMS/$DISTRO_ID
	cp /boot/memtest86+.bin $BASE_SYSTEMS/$DISTRO_ID/mt86plus
}

if [[ ! -d $BASE_SYSTEMS/$DISTRO_ID && -n "$1" && "x$1" == "xinstall" ]]; then
	installation
fi

if [[ -n "$1" && "x$1" == "xconfig" ]]; then
	config
fi
