#!/usr/bin/env bash

RECIPE_BASE=$(dirname $0)
DISTRO_ID=$(basename $RECIPE_BASE)
DISTRO_NAME=Memtest

config(){
	echo "label $DISTRO_ID"
	echo "  menu label ^$DISTRO_NAME"
	echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/mt86plus"
}

config_ipxe(){
	echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/mt86plus"

	cat <<-END
	:menujump-$DISTRO_ID
	item --key M $DISTRO_ID Run $DISTRO_NAME
	goto backjump-$DISTRO_ID

	:$DISTRO_ID
	chain $BASEURL_HTTPT$BASE_SYSTEMS_rel/$DISTRO_ID/mt86plus || goto failed
	END
}

installation(){
	mkdir -p $BASE_SYSTEMS/$DISTRO_ID
	cp /boot/memtest86+.bin $BASE_SYSTEMS/$DISTRO_ID/mt86plus
}

update(){
	return
}

case "$1" in
	install)
		[[ ! -d $BASE_SYSTEMS/$DISTRO_ID ]] && installation
		update
		;;
	config)
		config
		;;
	config_ipxe)
		config_ipxe
		;;
esac
