#!/usr/bin/env bash

RECIPE_BASE=$(dirname $0)
DISTRO_ID=$(basename $RECIPE_BASE)
DISTRO_NAME="HDD Local"

config(){
	echo "label $DISTRO_ID"
	echo "  menu label ^$DISTRO_NAME"
	echo "  localboot 0"
}

config_ipxe(){
	# Not neccessary as the installation has automatic BIOS-boot with the exit-feature
	return 0
}

installation(){
	return 0
}

if [[ ! -d $BASE_SYSTEMS/$DISTRO_ID && -n "$1" && "x$1" == "xinstall" ]]; then
	installation
fi

if [[ -n "$1" && "x$1" == "xconfig" ]]; then
	config
fi
if [[ -n "$1" && "x$1" == "xconfig_ipxe" ]]; then
	config_ipxe
fi
