#!/usr/bin/env bash

RECIPE_BASE=$(dirname $0)
DISTRO_ID=$(basename $RECIPE_BASE)
DISTRO_NAME="HDD Local"

config(){
	echo "label $DISTRO_ID"
	echo "  menu label ^$DISTRO_NAME"
	echo "  localboot 0"
}

config_ipxe(){
	# Not neccessary as the installation has automatic BIOS-boot with the exit-feature
	return 0
}

installation(){
	return 0
}

update(){
	return
}

case "$1" in
	install)
		[[ ! -d $BASE_SYSTEMS/$DISTRO_ID ]] && installation
		update
		;;
	config)
		config
		;;
	config_ipxe)
		config_ipxe
		;;
esac
