#!/usr/bin/env bash

RECIPE_BASE=$(dirname $0)
DISTRO_ID=$(basename $RECIPE_BASE)
DISTRO_NAME="Ubuntu 16.04 LiveCD"

config(){
	echo "label $DISTRO_ID"
	echo "  menu label ^$DISTRO_NAME"
	echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/casper/vmlinuz.efi"
	echo "  append     boot=casper initrd=$BASE_SYSTEMS_rel/$DISTRO_ID/casper/initrd.lz"
}

config_ipxe(){
	cat <<-END
	:menujump-$DISTRO_ID
	item $DISTRO_ID Boot $DISTRO_NAME
	goto backjump-$DISTRO_ID

	:$DISTRO_ID
	kernel $BASE_SYSTEMS_rel/$DISTRO_ID/casper/vmlinuz.efi boot=casper netboot=nfs nfsroot=$NFSHOST:$BASE_SYSTEMS/$DISTRO_ID/
	initrd $BASE_SYSTEMS_rel/$DISTRO_ID/casper/initrd.lz
	boot || goto failed
	END
}

installation(){
	iso=$(mktemp)
	dir=$(mktemp -d)
	wget ${MIRROR}-releases/16.04/ubuntu-16.04-desktop-amd64.iso -O $iso
	mount $iso $dir
	cp -r $dir $BASE_SYSTEMS/$DISTRO_ID
	umount $dir
	rmdir $dir
	rm $iso
}

update(){
	return
}

case "$1" in
	install)
		[[ ! -d $BASE_SYSTEMS/$DISTRO_ID ]] && installation
		update
		;;
	config)
		config
		;;
	config_ipxe)
		config_ipxe
		;;
esac
