#!/usr/bin/env bash

RECIPE_BASE=$(dirname $0)
DISTRO_ID=$(basename $RECIPE_BASE)
DISTRO_NAME="Ubuntu 14.04 Server Rescue"

config(){
	echo "label $DISTRO_ID"
	echo "  menu label ^$DISTRO_NAME"
	echo "  kernel     $BASE_SYSTEMS_rel/$DISTRO_ID/vmlinuz"
	echo "  append     netboot=nfs rootfstype=nfs4 root=/dev/nfs4 nfsroot=$NFSHOST:$BASE_SYSTEMS/$DISTRO_ID/ initrd=$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.img ip=dhcp"

}

config_ipxe(){

	cat <<-END
	:menujump-$DISTRO_ID
	item $DISTRO_ID Boot $DISTRO_NAME
	goto backjump-$DISTRO_ID

	:$DISTRO_ID
	kernel $BASEURL_HTTP/$BASE_SYSTEMS_rel/$DISTRO_ID/vmlinuz netboot=nfs rootfstype=nfs4 root=/dev/nfs4 nfsroot=$NFSHOST:$BASE_SYSTEMS/$DISTRO_ID/ ip=dhcp
	initrd $BASEURL_HTTP/$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.img
	boot || goto failed
	END

}

installation(){
	mkdir -p $BASE_SYSTEMS/$DISTRO_ID

	debootstrap --arch=amd64 trusty $BASE_SYSTEMS/$DISTRO_ID $MIRROR

	for i in dev dev/pts proc sys run; do
		mount -B /$i $BASE_SYSTEMS/$DISTRO_ID/$i
	done

	echo $DISTRO_ID > $BASE_SYSTEMS/$DISTRO_ID/etc/hostname

	chroot $BASE_SYSTEMS/$DISTRO_ID localedef -i de_DE -c -f UTF-8 de_DE.UTF-8
	chroot $BASE_SYSTEMS/$DISTRO_ID locale-gen de_DE.UTF-8
	chroot $BASE_SYSTEMS/$DISTRO_ID locale-gen en_US.UTF-8

	echo "grub-pc	grub-pc/mixed_legacy_and_grub2	boolean	true" | chroot $BASE_SYSTEMS/$DISTRO_ID debconf-set-selections
	echo "grub-pc	grub-pc/install_devices	multiselect	/dev/null" | chroot $BASE_SYSTEMS/$DISTRO_ID debconf-set-selections
	echo "grub-pc	grub-pc/install_devices_failed	boolean	true" | chroot $BASE_SYSTEMS/$DISTRO_ID debconf-set-selections
	chroot $BASE_SYSTEMS/$DISTRO_ID env DEBIAN_FRONTEND=noninteractive apt-get install -y vim linux-image-generic

	chroot $BASE_SYSTEMS/$DISTRO_ID useradd -Um --home-dir /home/user --uid 1000  --password '$6$2ez0KCz3$uBocmB2dW46YyyZPYw78gxkkxWcsRvr3.3hcLujZcjipab8MM6TtQsFqurb7hlVkqCHKbuCKiGsc3OC/wUp/A/' user
	chroot $BASE_SYSTEMS/$DISTRO_ID usermod -aG adm,cdrom,sudo,plugdev user
	chroot $BASE_SYSTEMS/$DISTRO_ID sed -i 's/BOOT=local/BOOT=nfs/' /etc/initramfs-tools/initramfs.conf
	chroot $BASE_SYSTEMS/$DISTRO_ID update-initramfs -u
	chmod 644 $BASE_SYSTEMS/$DISTRO_ID/boot/vmlinuz-*

	cat > $BASE_SYSTEMS/$DISTRO_ID/etc/network/interfaces <<-END
	auto lo
	iface lo inet loopback

	auto eth0
	iface eth0 inet dhcp
	END
}

update(){
	return
}

case "$1" in
	install)
		[[ ! -d $BASE_SYSTEMS/$DISTRO_ID ]] && installation
		update
		;;
	config)
		config
		;;
	config_ipxe)
		config_ipxe
		;;
esac
