#!/usr/bin/env bash

# copy this file for your new state

RECIPE_BASE=$(dirname $0)
DISTRO_ID=$(basename $RECIPE_BASE)
DISTRO_NAME=skelleton

config(){
	# here will be the config printed.
	# uncomment and adapt the entries
	#echo "label $DISTRO_ID"
	#echo "  menu label Ubuntu 14.04 Desktop rescue"
	#echo "  kernel     systems/$DISTRO_ID/vmlinuz"
	#echo "  append     netboot=nfs rootfstype=nfs4 root=/dev/nfs4 nfsroot=$NFSHOST:$BASE_SYSTEMS/$DISTRO_ID/ initrd=$BASE_SYSTEMS_rel/$DISTRO_ID/initrd.img ip=dhcp"
	return 0
}

installation(){
	# always do this at first. When setup.sh is called again, it will detect, that this system is already installed and won't do the effort again.
	mkdir -p $BASE_SYSTEMS/$DISTRO_ID
}

if [[ ! -d $BASE_SYSTEMS/$DISTRO_ID && -n "$1" && "x$1" == "xinstall" ]]; then
	installation
fi

if [[ -n "$1" && "x$1" == "xconfig" ]]; then
	config
fi
